# Generated by Django 3.2.7 on 2026-01-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_product_gallery_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='memberID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
