# Generated by Django 3.2.7 on 2026-01-31 00:00

from django.db import migrations, models


def move_banner_image_urls(apps, schema_editor):
    Blog = apps.get_model("account", "Blog")
    for blog in Blog.objects.all():
        val = getattr(blog, "banner_image", None)
        if not val:
            continue
        if isinstance(val, str) and val.strip().lower().startswith(("http://", "https://")):
            blog.banner_image_url = val.strip()
            blog.banner_image = ""
            blog.save(update_fields=["banner_image", "banner_image_url"])


def move_banner_image_urls_reverse(apps, schema_editor):
    Blog = apps.get_model("account", "Blog")
    for blog in Blog.objects.all():
        url = getattr(blog, "banner_image_url", None)
        val = getattr(blog, "banner_image", None)
        if url and not val:
            blog.banner_image = url
            blog.banner_image_url = ""
            blog.save(update_fields=["banner_image", "banner_image_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0020_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="banner_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(move_banner_image_urls, move_banner_image_urls_reverse),
        migrations.AlterField(
            model_name="blog",
            name="banner_image",
            field=models.ImageField(blank=True, null=True, upload_to="blogs/banners/"),
        ),
    ]

