# Generated by Django 3.2.7 on 2026-01-31 00:00

from django.db import migrations, models


def move_author_avatar_urls(apps, schema_editor):
    Blog = apps.get_model("account", "Blog")
    for blog in Blog.objects.all():
        val = getattr(blog, "author_avatar", None)
        if not val:
            continue
        if isinstance(val, str) and val.strip().lower().startswith(("http://", "https://")):
            blog.author_avatar_url = val.strip()
            blog.author_avatar = ""
            blog.save(update_fields=["author_avatar", "author_avatar_url"])


def move_author_avatar_urls_reverse(apps, schema_editor):
    Blog = apps.get_model("account", "Blog")
    for blog in Blog.objects.all():
        url = getattr(blog, "author_avatar_url", None)
        val = getattr(blog, "author_avatar", None)
        if url and not val:
            blog.author_avatar = url
            blog.author_avatar_url = ""
            blog.save(update_fields=["author_avatar", "author_avatar_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0021_blog_banner_image_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="author_avatar_url",
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(move_author_avatar_urls, move_author_avatar_urls_reverse),
        migrations.AlterField(
            model_name="blog",
            name="author_avatar",
            field=models.ImageField(blank=True, null=True, upload_to="blogs/authors/"),
        ),
    ]

