# Generated by Django 6.0.1 on 2026-01-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_blog_author_avatar_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_avatar_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='banner_image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
