# Generated by Django 3.2.7 on 2026-02-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_name',
        ),
    ]
