# Generated by Django 3.2.7 on 2026-02-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_remove_service_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's full name", max_length=200)),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('role', models.CharField(help_text='Job title/role', max_length=200)),
                ('text', models.TextField(help_text='Testimonial content')),
                ('image', models.ImageField(blank=True, help_text="Client's profile photo", null=True, upload_to='testimonials/')),
                ('linkedin', models.URLField(blank=True, default='/#', help_text='LinkedIn profile URL (use /# if not available)', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('sort_order', models.IntegerField(default=0, help_text='Order in which testimonials appear (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
