# Generated by Django 3.2.7 on 2026-02-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing',
            field=models.CharField(blank=True, help_text='Product pricing string (e.g., Free, ₹499/month, Custom Pricing)', max_length=100, null=True),
        ),
    ]
