# Generated by Django 3.2.7 on 2026-02-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_product_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pricing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
