# Generated by Django 3.2.7 on 2026-02-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_product_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='use_cases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
