# Generated by Django 3.2.7 on 2026-02-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_teammember_use_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='use_cases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
