# Generated by Django 3.2.7 on 2026-02-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_service_use_cases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sortOrder', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='sortOrder',
            field=models.IntegerField(default=0, help_text='Order in which projects appear (lower numbers first)'),
        ),
    ]
