# Generated by Django 3.2.7 on 2026-02-27 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def populate_empty_slugs(apps, schema_editor):
    Service = apps.get_model('account', 'Service')
    # Only run if the table has the slug column (after AddField without unique)
    try:
        qs = Service.objects.filter(models.Q(slug='') | models.Q(slug__isnull=True))
    except Exception:
        return

    for s in qs:
        base = slugify(getattr(s, 'title', '') or 'service')[:240]
        if not base:
            base = 'service'
        candidate = base
        counter = 1
        while Service.objects.filter(slug=candidate).exclude(pk=s.pk).exists():
            candidate = f"{base[:235]}-{counter}"
            counter += 1
        s.slug = candidate
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20260221_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('designation', models.CharField(blank=True, choices=[('Full Stack Developer', 'Full Stack Developer'), ('Intern', 'Intern'), ('ML/AI Intern', 'ML/AI Intern'), ('Software Developer Intern', 'Software Developer Intern'), ('GIS Intern', 'GIS Intern'), ('GIS Project Manager', 'GIS Project Manager')], max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'ordering': ['-created_at'],
            },
        ),
        # Add slug field without uniqueness first so we can populate values
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, db_index=True),
        ),
        # Populate empty/null slugs now that the column exists
        migrations.RunPython(populate_empty_slugs, reverse_code=migrations.RunPython.noop),
        # Add uniqueness constraint after data is populated
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=['slug'], name='service_slug_unique'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='account.employeeprofile')),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
