# Generated by Django 3.2.7 on 2026-02-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_auto_20260228_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='gisservice',
            name='explore',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
