# Generated by Django 6.0.1 on 2026-02-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_gisservice_explore'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='explore',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
