# Generated by Django 6.0.1 on 2026-02-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_employeedocument_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
