# Generated by Django 6.0.1 on 2026-02-28 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_alter_employeeprofile_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goal_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='rejoin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spare_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='projects', to='account.teammember'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='working_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
