# Generated by Django 6.0.1 on 2026-03-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_project_goal_deadline_project_image_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
