# Generated by Django 6.0.1 on 2026-03-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_alter_employeedocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employee_team_members',
            field=models.ManyToManyField(blank=True, related_name='projects', to='account.employeeprofile'),
        ),
    ]
