# Generated by Django 6.0.1 on 2026-03-05 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_employee_ticket_and_plan_ticket_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTicketAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee-ticket-attachments/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='employeeticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeticket',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employee_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='account.employeeprofile'),
        ),
        migrations.AddField(
            model_name='employeeticket',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employeeticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name='employeeticket',
            index=models.Index(fields=['ticket_number'], name='account_emp_ticket__24e57b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeticket',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='account_emp_status_667abb_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeticket',
            index=models.Index(fields=['assigned_to', 'created_at'], name='account_emp_assigne_17b4bc_idx'),
        ),
        migrations.AddField(
            model_name='employeeticketassignmenthistory',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignment_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeticketassignmenthistory',
            name='from_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignment_from_events', to='account.employeeprofile'),
        ),
        migrations.AddField(
            model_name='employeeticketassignmenthistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='account.employeeticket'),
        ),
        migrations.AddField(
            model_name='employeeticketassignmenthistory',
            name='to_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignment_to_events', to='account.employeeprofile'),
        ),
        migrations.AddField(
            model_name='employeeticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='account.employeeticket'),
        ),
        migrations.AddIndex(
            model_name='employeeticketassignmenthistory',
            index=models.Index(fields=['ticket', 'at'], name='account_emp_ticket__fb27bc_idx'),
        ),
    ]
