# Generated by Django 6.0.1 on 2026-03-05 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_employeeticketcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('member', 'Member'), ('lead', 'Lead'), ('pm', 'Project Manager')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='account.employeeprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='account.project')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project', 'is_active'], name='account_pro_project_cf1812_idx'), models.Index(fields=['employee', 'is_active'], name='account_pro_employe_0538a5_idx')],
                'unique_together': {('project', 'employee')},
            },
        ),
    ]
